// Code generated by protoc-gen-go. DO NOT EDIT.
// source: baidu.proto

package baidu

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Device_DeviceType int32

const (
	Device_PHONE          Device_DeviceType = 1
	Device_TABLET         Device_DeviceType = 2
	Device_SMART_TV       Device_DeviceType = 3
	Device_OUTDOOR_SCREEN Device_DeviceType = 4
)

var Device_DeviceType_name = map[int32]string{
	1: "PHONE",
	2: "TABLET",
	3: "SMART_TV",
	4: "OUTDOOR_SCREEN",
}
var Device_DeviceType_value = map[string]int32{
	"PHONE":          1,
	"TABLET":         2,
	"SMART_TV":       3,
	"OUTDOOR_SCREEN": 4,
}

func (x Device_DeviceType) Enum() *Device_DeviceType {
	p := new(Device_DeviceType)
	*p = x
	return p
}
func (x Device_DeviceType) String() string {
	return proto.EnumName(Device_DeviceType_name, int32(x))
}
func (x *Device_DeviceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_DeviceType_value, data, "Device_DeviceType")
	if err != nil {
		return err
	}
	*x = Device_DeviceType(value)
	return nil
}
func (Device_DeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{4, 0}
}

type Device_OsType int32

const (
	Device_ANDROID Device_OsType = 1
	Device_IOS     Device_OsType = 2
)

var Device_OsType_name = map[int32]string{
	1: "ANDROID",
	2: "IOS",
}
var Device_OsType_value = map[string]int32{
	"ANDROID": 1,
	"IOS":     2,
}

func (x Device_OsType) Enum() *Device_OsType {
	p := new(Device_OsType)
	*p = x
	return p
}
func (x Device_OsType) String() string {
	return proto.EnumName(Device_OsType_name, int32(x))
}
func (x *Device_OsType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_OsType_value, data, "Device_OsType")
	if err != nil {
		return err
	}
	*x = Device_OsType(value)
	return nil
}
func (Device_OsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{4, 1}
}

type Network_ConnectionType int32

const (
	Network_CONNECTION_UNKNOWN Network_ConnectionType = 0
	Network_CELL_UNKNOWN       Network_ConnectionType = 1
	Network_CELL_2G            Network_ConnectionType = 2
	Network_CELL_3G            Network_ConnectionType = 3
	Network_CELL_4G            Network_ConnectionType = 4
	Network_CELL_5G            Network_ConnectionType = 5
	Network_WIFI               Network_ConnectionType = 100
	Network_ETHERNET           Network_ConnectionType = 101
	Network_NEW_TYPE           Network_ConnectionType = 999
)

var Network_ConnectionType_name = map[int32]string{
	0:   "CONNECTION_UNKNOWN",
	1:   "CELL_UNKNOWN",
	2:   "CELL_2G",
	3:   "CELL_3G",
	4:   "CELL_4G",
	5:   "CELL_5G",
	100: "WIFI",
	101: "ETHERNET",
	999: "NEW_TYPE",
}
var Network_ConnectionType_value = map[string]int32{
	"CONNECTION_UNKNOWN": 0,
	"CELL_UNKNOWN":       1,
	"CELL_2G":            2,
	"CELL_3G":            3,
	"CELL_4G":            4,
	"CELL_5G":            5,
	"WIFI":               100,
	"ETHERNET":           101,
	"NEW_TYPE":           999,
}

func (x Network_ConnectionType) Enum() *Network_ConnectionType {
	p := new(Network_ConnectionType)
	*p = x
	return p
}
func (x Network_ConnectionType) String() string {
	return proto.EnumName(Network_ConnectionType_name, int32(x))
}
func (x *Network_ConnectionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Network_ConnectionType_value, data, "Network_ConnectionType")
	if err != nil {
		return err
	}
	*x = Network_ConnectionType(value)
	return nil
}
func (Network_ConnectionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{6, 0}
}

type Network_OperatorType int32

const (
	Network_UNKNOWN_OPERATOR Network_OperatorType = 0
	Network_CHINA_MOBILE     Network_OperatorType = 1
	Network_CHINA_TELECOM    Network_OperatorType = 2
	Network_CHINA_UNICOM     Network_OperatorType = 3
	Network_OTHER_OPERATOR   Network_OperatorType = 99
)

var Network_OperatorType_name = map[int32]string{
	0:  "UNKNOWN_OPERATOR",
	1:  "CHINA_MOBILE",
	2:  "CHINA_TELECOM",
	3:  "CHINA_UNICOM",
	99: "OTHER_OPERATOR",
}
var Network_OperatorType_value = map[string]int32{
	"UNKNOWN_OPERATOR": 0,
	"CHINA_MOBILE":     1,
	"CHINA_TELECOM":    2,
	"CHINA_UNICOM":     3,
	"OTHER_OPERATOR":   99,
}

func (x Network_OperatorType) Enum() *Network_OperatorType {
	p := new(Network_OperatorType)
	*p = x
	return p
}
func (x Network_OperatorType) String() string {
	return proto.EnumName(Network_OperatorType_name, int32(x))
}
func (x *Network_OperatorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Network_OperatorType_value, data, "Network_OperatorType")
	if err != nil {
		return err
	}
	*x = Network_OperatorType(value)
	return nil
}
func (Network_OperatorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{6, 1}
}

type Gps_CoordinateType int32

const (
	Gps_WGS84 Gps_CoordinateType = 1
	Gps_GCJ02 Gps_CoordinateType = 2
	Gps_BD09  Gps_CoordinateType = 3
)

var Gps_CoordinateType_name = map[int32]string{
	1: "WGS84",
	2: "GCJ02",
	3: "BD09",
}
var Gps_CoordinateType_value = map[string]int32{
	"WGS84": 1,
	"GCJ02": 2,
	"BD09":  3,
}

func (x Gps_CoordinateType) Enum() *Gps_CoordinateType {
	p := new(Gps_CoordinateType)
	*p = x
	return p
}
func (x Gps_CoordinateType) String() string {
	return proto.EnumName(Gps_CoordinateType_name, int32(x))
}
func (x *Gps_CoordinateType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Gps_CoordinateType_value, data, "Gps_CoordinateType")
	if err != nil {
		return err
	}
	*x = Gps_CoordinateType(value)
	return nil
}
func (Gps_CoordinateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{7, 0}
}

type Tracking_TrackingEvent int32

const (
	Tracking_AD_CLICK                  Tracking_TrackingEvent = 0
	Tracking_AD_EXPOSURE               Tracking_TrackingEvent = 1
	Tracking_AD_CLOSE                  Tracking_TrackingEvent = 2
	Tracking_VIDEO_AD_START            Tracking_TrackingEvent = 101000
	Tracking_VIDEO_AD_FULL_SCREEN      Tracking_TrackingEvent = 101001
	Tracking_VIDEO_AD_END              Tracking_TrackingEvent = 101002
	Tracking_VIDEO_AD_START_CARD_CLICK Tracking_TrackingEvent = 101003
	Tracking_APP_AD_DOWNLOAD           Tracking_TrackingEvent = 102000
	Tracking_APP_AD_INSTALL            Tracking_TrackingEvent = 102001
	Tracking_APP_AD_ACTIVE             Tracking_TrackingEvent = 102002
)

var Tracking_TrackingEvent_name = map[int32]string{
	0:      "AD_CLICK",
	1:      "AD_EXPOSURE",
	2:      "AD_CLOSE",
	101000: "VIDEO_AD_START",
	101001: "VIDEO_AD_FULL_SCREEN",
	101002: "VIDEO_AD_END",
	101003: "VIDEO_AD_START_CARD_CLICK",
	102000: "APP_AD_DOWNLOAD",
	102001: "APP_AD_INSTALL",
	102002: "APP_AD_ACTIVE",
}
var Tracking_TrackingEvent_value = map[string]int32{
	"AD_CLICK":                  0,
	"AD_EXPOSURE":               1,
	"AD_CLOSE":                  2,
	"VIDEO_AD_START":            101000,
	"VIDEO_AD_FULL_SCREEN":      101001,
	"VIDEO_AD_END":              101002,
	"VIDEO_AD_START_CARD_CLICK": 101003,
	"APP_AD_DOWNLOAD":           102000,
	"APP_AD_INSTALL":            102001,
	"APP_AD_ACTIVE":             102002,
}

func (x Tracking_TrackingEvent) Enum() *Tracking_TrackingEvent {
	p := new(Tracking_TrackingEvent)
	*p = x
	return p
}
func (x Tracking_TrackingEvent) String() string {
	return proto.EnumName(Tracking_TrackingEvent_name, int32(x))
}
func (x *Tracking_TrackingEvent) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Tracking_TrackingEvent_value, data, "Tracking_TrackingEvent")
	if err != nil {
		return err
	}
	*x = Tracking_TrackingEvent(value)
	return nil
}
func (Tracking_TrackingEvent) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{8, 0}
}

type Video_CopyRight int32

const (
	Video_CR_NONE  Video_CopyRight = 0
	Video_CR_EXIST Video_CopyRight = 1
	Video_CR_UGC   Video_CopyRight = 2
	Video_CR_OTHER Video_CopyRight = 3
)

var Video_CopyRight_name = map[int32]string{
	0: "CR_NONE",
	1: "CR_EXIST",
	2: "CR_UGC",
	3: "CR_OTHER",
}
var Video_CopyRight_value = map[string]int32{
	"CR_NONE":  0,
	"CR_EXIST": 1,
	"CR_UGC":   2,
	"CR_OTHER": 3,
}

func (x Video_CopyRight) Enum() *Video_CopyRight {
	p := new(Video_CopyRight)
	*p = x
	return p
}
func (x Video_CopyRight) String() string {
	return proto.EnumName(Video_CopyRight_name, int32(x))
}
func (x *Video_CopyRight) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Video_CopyRight_value, data, "Video_CopyRight")
	if err != nil {
		return err
	}
	*x = Video_CopyRight(value)
	return nil
}
func (Video_CopyRight) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{9, 0}
}

type Video_MaterialFormat int32

const (
	Video_VIDEO_TCL_MP4 Video_MaterialFormat = 11
	Video_VIDEO_TCL_TS  Video_MaterialFormat = 12
	Video_VIDEO_TS      Video_MaterialFormat = 13
)

var Video_MaterialFormat_name = map[int32]string{
	11: "VIDEO_TCL_MP4",
	12: "VIDEO_TCL_TS",
	13: "VIDEO_TS",
}
var Video_MaterialFormat_value = map[string]int32{
	"VIDEO_TCL_MP4": 11,
	"VIDEO_TCL_TS":  12,
	"VIDEO_TS":      13,
}

func (x Video_MaterialFormat) Enum() *Video_MaterialFormat {
	p := new(Video_MaterialFormat)
	*p = x
	return p
}
func (x Video_MaterialFormat) String() string {
	return proto.EnumName(Video_MaterialFormat_name, int32(x))
}
func (x *Video_MaterialFormat) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Video_MaterialFormat_value, data, "Video_MaterialFormat")
	if err != nil {
		return err
	}
	*x = Video_MaterialFormat(value)
	return nil
}
func (Video_MaterialFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{9, 1}
}

type MobadsRequest_RequestProtocolType int32

const (
	MobadsRequest_UNKNOWN_PROTOCOL_TYPE MobadsRequest_RequestProtocolType = 0
	MobadsRequest_HTTP_PROTOCOL_TYPE    MobadsRequest_RequestProtocolType = 1
	MobadsRequest_HTTPS_PROTOCOL_TYPE   MobadsRequest_RequestProtocolType = 2
)

var MobadsRequest_RequestProtocolType_name = map[int32]string{
	0: "UNKNOWN_PROTOCOL_TYPE",
	1: "HTTP_PROTOCOL_TYPE",
	2: "HTTPS_PROTOCOL_TYPE",
}
var MobadsRequest_RequestProtocolType_value = map[string]int32{
	"UNKNOWN_PROTOCOL_TYPE": 0,
	"HTTP_PROTOCOL_TYPE":    1,
	"HTTPS_PROTOCOL_TYPE":   2,
}

func (x MobadsRequest_RequestProtocolType) Enum() *MobadsRequest_RequestProtocolType {
	p := new(MobadsRequest_RequestProtocolType)
	*p = x
	return p
}
func (x MobadsRequest_RequestProtocolType) String() string {
	return proto.EnumName(MobadsRequest_RequestProtocolType_name, int32(x))
}
func (x *MobadsRequest_RequestProtocolType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MobadsRequest_RequestProtocolType_value, data, "MobadsRequest_RequestProtocolType")
	if err != nil {
		return err
	}
	*x = MobadsRequest_RequestProtocolType(value)
	return nil
}
func (MobadsRequest_RequestProtocolType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{12, 0}
}

type MaterialMeta_CreativeType int32

const (
	MaterialMeta_NO_TYPE   MaterialMeta_CreativeType = 0
	MaterialMeta_TEXT      MaterialMeta_CreativeType = 1
	MaterialMeta_IMAGE     MaterialMeta_CreativeType = 2
	MaterialMeta_TEXT_ICON MaterialMeta_CreativeType = 3
	MaterialMeta_VIDEO     MaterialMeta_CreativeType = 4
)

var MaterialMeta_CreativeType_name = map[int32]string{
	0: "NO_TYPE",
	1: "TEXT",
	2: "IMAGE",
	3: "TEXT_ICON",
	4: "VIDEO",
}
var MaterialMeta_CreativeType_value = map[string]int32{
	"NO_TYPE":   0,
	"TEXT":      1,
	"IMAGE":     2,
	"TEXT_ICON": 3,
	"VIDEO":     4,
}

func (x MaterialMeta_CreativeType) Enum() *MaterialMeta_CreativeType {
	p := new(MaterialMeta_CreativeType)
	*p = x
	return p
}
func (x MaterialMeta_CreativeType) String() string {
	return proto.EnumName(MaterialMeta_CreativeType_name, int32(x))
}
func (x *MaterialMeta_CreativeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MaterialMeta_CreativeType_value, data, "MaterialMeta_CreativeType")
	if err != nil {
		return err
	}
	*x = MaterialMeta_CreativeType(value)
	return nil
}
func (MaterialMeta_CreativeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{14, 0}
}

type MaterialMeta_InteractionType int32

const (
	MaterialMeta_NO_INTERACTION MaterialMeta_InteractionType = 0
	MaterialMeta_SURFING        MaterialMeta_InteractionType = 1
	MaterialMeta_DOWNLOAD       MaterialMeta_InteractionType = 2
	MaterialMeta_DEEPLINK       MaterialMeta_InteractionType = 3
)

var MaterialMeta_InteractionType_name = map[int32]string{
	0: "NO_INTERACTION",
	1: "SURFING",
	2: "DOWNLOAD",
	3: "DEEPLINK",
}
var MaterialMeta_InteractionType_value = map[string]int32{
	"NO_INTERACTION": 0,
	"SURFING":        1,
	"DOWNLOAD":       2,
	"DEEPLINK":       3,
}

func (x MaterialMeta_InteractionType) Enum() *MaterialMeta_InteractionType {
	p := new(MaterialMeta_InteractionType)
	*p = x
	return p
}
func (x MaterialMeta_InteractionType) String() string {
	return proto.EnumName(MaterialMeta_InteractionType_name, int32(x))
}
func (x *MaterialMeta_InteractionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MaterialMeta_InteractionType_value, data, "MaterialMeta_InteractionType")
	if err != nil {
		return err
	}
	*x = MaterialMeta_InteractionType(value)
	return nil
}
func (MaterialMeta_InteractionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{14, 1}
}

type Version struct {
	Major                *uint32  `protobuf:"varint,1,opt,name=major,def=0" json:"major,omitempty"`
	Minor                *uint32  `protobuf:"varint,2,opt,name=minor,def=0" json:"minor,omitempty"`
	Micro                *uint32  `protobuf:"varint,3,opt,name=micro,def=0" json:"micro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{0}
}
func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (dst *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(dst, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

const Default_Version_Major uint32 = 0
const Default_Version_Minor uint32 = 0
const Default_Version_Micro uint32 = 0

func (m *Version) GetMajor() uint32 {
	if m != nil && m.Major != nil {
		return *m.Major
	}
	return Default_Version_Major
}

func (m *Version) GetMinor() uint32 {
	if m != nil && m.Minor != nil {
		return *m.Minor
	}
	return Default_Version_Minor
}

func (m *Version) GetMicro() uint32 {
	if m != nil && m.Micro != nil {
		return *m.Micro
	}
	return Default_Version_Micro
}

type App struct {
	AppId                *string  `protobuf:"bytes,1,opt,name=app_id,json=appId,def=" json:"app_id,omitempty"`
	ChannelId            *string  `protobuf:"bytes,2,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	AppVersion           *Version `protobuf:"bytes,3,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
	AppPackage           *string  `protobuf:"bytes,4,opt,name=app_package,json=appPackage" json:"app_package,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{1}
}
func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (dst *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(dst, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *App) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

func (m *App) GetAppVersion() *Version {
	if m != nil {
		return m.AppVersion
	}
	return nil
}

func (m *App) GetAppPackage() string {
	if m != nil && m.AppPackage != nil {
		return *m.AppPackage
	}
	return ""
}

type UdId struct {
	Idfa                 *string  `protobuf:"bytes,1,opt,name=idfa,def=" json:"idfa,omitempty"`
	Imei                 *string  `protobuf:"bytes,2,opt,name=imei,def=" json:"imei,omitempty"`
	Mac                  *string  `protobuf:"bytes,3,opt,name=mac,def=" json:"mac,omitempty"`
	ImeiMd5              *string  `protobuf:"bytes,4,opt,name=imei_md5,json=imeiMd5,def=" json:"imei_md5,omitempty"`
	AndroidId            *string  `protobuf:"bytes,5,opt,name=android_id,json=androidId,def=" json:"android_id,omitempty"`
	Baiduid              *string  `protobuf:"bytes,6,opt,name=baiduid,def=" json:"baiduid,omitempty"`
	Cuid                 *string  `protobuf:"bytes,7,opt,name=cuid,def=" json:"cuid,omitempty"`
	IdfaMd5              *string  `protobuf:"bytes,8,opt,name=idfa_md5,json=idfaMd5,def=" json:"idfa_md5,omitempty"`
	AndroididMd5         *string  `protobuf:"bytes,9,opt,name=androidid_md5,json=androididMd5,def=" json:"androidid_md5,omitempty"`
	Passport             *string  `protobuf:"bytes,10,opt,name=passport,def=" json:"passport,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UdId) Reset()         { *m = UdId{} }
func (m *UdId) String() string { return proto.CompactTextString(m) }
func (*UdId) ProtoMessage()    {}
func (*UdId) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{2}
}
func (m *UdId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UdId.Unmarshal(m, b)
}
func (m *UdId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UdId.Marshal(b, m, deterministic)
}
func (dst *UdId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UdId.Merge(dst, src)
}
func (m *UdId) XXX_Size() int {
	return xxx_messageInfo_UdId.Size(m)
}
func (m *UdId) XXX_DiscardUnknown() {
	xxx_messageInfo_UdId.DiscardUnknown(m)
}

var xxx_messageInfo_UdId proto.InternalMessageInfo

func (m *UdId) GetIdfa() string {
	if m != nil && m.Idfa != nil {
		return *m.Idfa
	}
	return ""
}

func (m *UdId) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *UdId) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *UdId) GetImeiMd5() string {
	if m != nil && m.ImeiMd5 != nil {
		return *m.ImeiMd5
	}
	return ""
}

func (m *UdId) GetAndroidId() string {
	if m != nil && m.AndroidId != nil {
		return *m.AndroidId
	}
	return ""
}

func (m *UdId) GetBaiduid() string {
	if m != nil && m.Baiduid != nil {
		return *m.Baiduid
	}
	return ""
}

func (m *UdId) GetCuid() string {
	if m != nil && m.Cuid != nil {
		return *m.Cuid
	}
	return ""
}

func (m *UdId) GetIdfaMd5() string {
	if m != nil && m.IdfaMd5 != nil {
		return *m.IdfaMd5
	}
	return ""
}

func (m *UdId) GetAndroididMd5() string {
	if m != nil && m.AndroididMd5 != nil {
		return *m.AndroididMd5
	}
	return ""
}

func (m *UdId) GetPassport() string {
	if m != nil && m.Passport != nil {
		return *m.Passport
	}
	return ""
}

type Size struct {
	Width                *uint32  `protobuf:"varint,1,opt,name=width,def=0" json:"width,omitempty"`
	Height               *uint32  `protobuf:"varint,2,opt,name=height,def=0" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{3}
}
func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (dst *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(dst, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

const Default_Size_Width uint32 = 0
const Default_Size_Height uint32 = 0

func (m *Size) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return Default_Size_Width
}

func (m *Size) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return Default_Size_Height
}

type Device struct {
	DeviceType           *Device_DeviceType `protobuf:"varint,1,opt,name=device_type,json=deviceType,enum=baidu.Device_DeviceType" json:"device_type,omitempty"`
	OsType               *Device_OsType     `protobuf:"varint,2,opt,name=os_type,json=osType,enum=baidu.Device_OsType" json:"os_type,omitempty"`
	OsVersion            *Version           `protobuf:"bytes,3,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
	Vendor               []byte             `protobuf:"bytes,4,opt,name=vendor,def=" json:"vendor,omitempty"`
	Model                []byte             `protobuf:"bytes,5,opt,name=model,def=" json:"model,omitempty"`
	Udid                 *UdId              `protobuf:"bytes,6,opt,name=udid" json:"udid,omitempty"`
	ScreenSize           *Size              `protobuf:"bytes,7,opt,name=screen_size,json=screenSize" json:"screen_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{4}
}
func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (dst *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(dst, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetDeviceType() Device_DeviceType {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return Device_PHONE
}

func (m *Device) GetOsType() Device_OsType {
	if m != nil && m.OsType != nil {
		return *m.OsType
	}
	return Device_ANDROID
}

func (m *Device) GetOsVersion() *Version {
	if m != nil {
		return m.OsVersion
	}
	return nil
}

func (m *Device) GetVendor() []byte {
	if m != nil {
		return m.Vendor
	}
	return nil
}

func (m *Device) GetModel() []byte {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *Device) GetUdid() *UdId {
	if m != nil {
		return m.Udid
	}
	return nil
}

func (m *Device) GetScreenSize() *Size {
	if m != nil {
		return m.ScreenSize
	}
	return nil
}

type WiFiAp struct {
	ApMac                *string  `protobuf:"bytes,1,opt,name=ap_mac,json=apMac" json:"ap_mac,omitempty"`
	Rssi                 *int32   `protobuf:"varint,2,opt,name=rssi" json:"rssi,omitempty"`
	ApName               []byte   `protobuf:"bytes,3,opt,name=ap_name,json=apName" json:"ap_name,omitempty"`
	IsConnected          *bool    `protobuf:"varint,4,opt,name=is_connected,json=isConnected" json:"is_connected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WiFiAp) Reset()         { *m = WiFiAp{} }
func (m *WiFiAp) String() string { return proto.CompactTextString(m) }
func (*WiFiAp) ProtoMessage()    {}
func (*WiFiAp) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{5}
}
func (m *WiFiAp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WiFiAp.Unmarshal(m, b)
}
func (m *WiFiAp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WiFiAp.Marshal(b, m, deterministic)
}
func (dst *WiFiAp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WiFiAp.Merge(dst, src)
}
func (m *WiFiAp) XXX_Size() int {
	return xxx_messageInfo_WiFiAp.Size(m)
}
func (m *WiFiAp) XXX_DiscardUnknown() {
	xxx_messageInfo_WiFiAp.DiscardUnknown(m)
}

var xxx_messageInfo_WiFiAp proto.InternalMessageInfo

func (m *WiFiAp) GetApMac() string {
	if m != nil && m.ApMac != nil {
		return *m.ApMac
	}
	return ""
}

func (m *WiFiAp) GetRssi() int32 {
	if m != nil && m.Rssi != nil {
		return *m.Rssi
	}
	return 0
}

func (m *WiFiAp) GetApName() []byte {
	if m != nil {
		return m.ApName
	}
	return nil
}

func (m *WiFiAp) GetIsConnected() bool {
	if m != nil && m.IsConnected != nil {
		return *m.IsConnected
	}
	return false
}

type Network struct {
	Ipv4                 *string                 `protobuf:"bytes,1,opt,name=ipv4" json:"ipv4,omitempty"`
	ConnectionType       *Network_ConnectionType `protobuf:"varint,2,opt,name=connection_type,json=connectionType,enum=baidu.Network_ConnectionType" json:"connection_type,omitempty"`
	OperatorType         *Network_OperatorType   `protobuf:"varint,3,opt,name=operator_type,json=operatorType,enum=baidu.Network_OperatorType" json:"operator_type,omitempty"`
	CellularId           *string                 `protobuf:"bytes,4,opt,name=cellular_id,json=cellularId" json:"cellular_id,omitempty"`
	WifiAps              []*WiFiAp               `protobuf:"bytes,5,rep,name=wifi_aps,json=wifiAps" json:"wifi_aps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{6}
}
func (m *Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Network.Unmarshal(m, b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Network.Marshal(b, m, deterministic)
}
func (dst *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(dst, src)
}
func (m *Network) XXX_Size() int {
	return xxx_messageInfo_Network.Size(m)
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func (m *Network) GetIpv4() string {
	if m != nil && m.Ipv4 != nil {
		return *m.Ipv4
	}
	return ""
}

func (m *Network) GetConnectionType() Network_ConnectionType {
	if m != nil && m.ConnectionType != nil {
		return *m.ConnectionType
	}
	return Network_CONNECTION_UNKNOWN
}

func (m *Network) GetOperatorType() Network_OperatorType {
	if m != nil && m.OperatorType != nil {
		return *m.OperatorType
	}
	return Network_UNKNOWN_OPERATOR
}

func (m *Network) GetCellularId() string {
	if m != nil && m.CellularId != nil {
		return *m.CellularId
	}
	return ""
}

func (m *Network) GetWifiAps() []*WiFiAp {
	if m != nil {
		return m.WifiAps
	}
	return nil
}

type Gps struct {
	CoordinateType       *Gps_CoordinateType `protobuf:"varint,1,opt,name=coordinate_type,json=coordinateType,enum=baidu.Gps_CoordinateType" json:"coordinate_type,omitempty"`
	Longitude            *float64            `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Latitude             *float64            `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
	Timestamp            *uint32             `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Gps) Reset()         { *m = Gps{} }
func (m *Gps) String() string { return proto.CompactTextString(m) }
func (*Gps) ProtoMessage()    {}
func (*Gps) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{7}
}
func (m *Gps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gps.Unmarshal(m, b)
}
func (m *Gps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gps.Marshal(b, m, deterministic)
}
func (dst *Gps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gps.Merge(dst, src)
}
func (m *Gps) XXX_Size() int {
	return xxx_messageInfo_Gps.Size(m)
}
func (m *Gps) XXX_DiscardUnknown() {
	xxx_messageInfo_Gps.DiscardUnknown(m)
}

var xxx_messageInfo_Gps proto.InternalMessageInfo

func (m *Gps) GetCoordinateType() Gps_CoordinateType {
	if m != nil && m.CoordinateType != nil {
		return *m.CoordinateType
	}
	return Gps_WGS84
}

func (m *Gps) GetLongitude() float64 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *Gps) GetLatitude() float64 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *Gps) GetTimestamp() uint32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type Tracking struct {
	TrackingEvent        *Tracking_TrackingEvent `protobuf:"varint,1,opt,name=tracking_event,json=trackingEvent,enum=baidu.Tracking_TrackingEvent" json:"tracking_event,omitempty"`
	TrackingUrl          []string                `protobuf:"bytes,2,rep,name=tracking_url,json=trackingUrl" json:"tracking_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Tracking) Reset()         { *m = Tracking{} }
func (m *Tracking) String() string { return proto.CompactTextString(m) }
func (*Tracking) ProtoMessage()    {}
func (*Tracking) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{8}
}
func (m *Tracking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracking.Unmarshal(m, b)
}
func (m *Tracking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracking.Marshal(b, m, deterministic)
}
func (dst *Tracking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracking.Merge(dst, src)
}
func (m *Tracking) XXX_Size() int {
	return xxx_messageInfo_Tracking.Size(m)
}
func (m *Tracking) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracking.DiscardUnknown(m)
}

var xxx_messageInfo_Tracking proto.InternalMessageInfo

func (m *Tracking) GetTrackingEvent() Tracking_TrackingEvent {
	if m != nil && m.TrackingEvent != nil {
		return *m.TrackingEvent
	}
	return Tracking_AD_CLICK
}

func (m *Tracking) GetTrackingUrl() []string {
	if m != nil {
		return m.TrackingUrl
	}
	return nil
}

type Video struct {
	Title                []byte                 `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	ContentLength        *uint32                `protobuf:"varint,2,opt,name=content_length,json=contentLength" json:"content_length,omitempty"`
	Copyright            *Video_CopyRight       `protobuf:"varint,3,opt,name=copyright,enum=baidu.Video_CopyRight" json:"copyright,omitempty"`
	MaterialFormat       []Video_MaterialFormat `protobuf:"varint,4,rep,name=material_format,json=materialFormat,enum=baidu.Video_MaterialFormat" json:"material_format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{9}
}
func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (dst *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(dst, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *Video) GetContentLength() uint32 {
	if m != nil && m.ContentLength != nil {
		return *m.ContentLength
	}
	return 0
}

func (m *Video) GetCopyright() Video_CopyRight {
	if m != nil && m.Copyright != nil {
		return *m.Copyright
	}
	return Video_CR_NONE
}

func (m *Video) GetMaterialFormat() []Video_MaterialFormat {
	if m != nil {
		return m.MaterialFormat
	}
	return nil
}

type Page struct {
	Url                  []byte   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Title                []byte   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	SourceUrl            []byte   `protobuf:"bytes,3,opt,name=source_url,json=sourceUrl" json:"source_url,omitempty"`
	ContentId            *string  `protobuf:"bytes,4,opt,name=content_id,json=contentId" json:"content_id,omitempty"`
	ContentCategory      [][]byte `protobuf:"bytes,5,rep,name=content_category,json=contentCategory" json:"content_category,omitempty"`
	ContentLabel         [][]byte `protobuf:"bytes,6,rep,name=content_label,json=contentLabel" json:"content_label,omitempty"`
	AuthorId             *string  `protobuf:"bytes,7,opt,name=author_id,json=authorId" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{10}
}
func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (dst *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(dst, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetUrl() []byte {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *Page) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *Page) GetSourceUrl() []byte {
	if m != nil {
		return m.SourceUrl
	}
	return nil
}

func (m *Page) GetContentId() string {
	if m != nil && m.ContentId != nil {
		return *m.ContentId
	}
	return ""
}

func (m *Page) GetContentCategory() [][]byte {
	if m != nil {
		return m.ContentCategory
	}
	return nil
}

func (m *Page) GetContentLabel() [][]byte {
	if m != nil {
		return m.ContentLabel
	}
	return nil
}

func (m *Page) GetAuthorId() string {
	if m != nil && m.AuthorId != nil {
		return *m.AuthorId
	}
	return ""
}

type AdSlot struct {
	AdslotId             *string  `protobuf:"bytes,1,opt,name=adslot_id,json=adslotId" json:"adslot_id,omitempty"`
	AdslotSize           *Size    `protobuf:"bytes,2,opt,name=adslot_size,json=adslotSize" json:"adslot_size,omitempty"`
	Topics               [][]byte `protobuf:"bytes,3,rep,name=topics" json:"topics,omitempty"`
	Video                *Video   `protobuf:"bytes,4,opt,name=video" json:"video,omitempty"`
	Ctkey                *string  `protobuf:"bytes,5,opt,name=ctkey" json:"ctkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdSlot) Reset()         { *m = AdSlot{} }
func (m *AdSlot) String() string { return proto.CompactTextString(m) }
func (*AdSlot) ProtoMessage()    {}
func (*AdSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{11}
}
func (m *AdSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdSlot.Unmarshal(m, b)
}
func (m *AdSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdSlot.Marshal(b, m, deterministic)
}
func (dst *AdSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdSlot.Merge(dst, src)
}
func (m *AdSlot) XXX_Size() int {
	return xxx_messageInfo_AdSlot.Size(m)
}
func (m *AdSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_AdSlot.DiscardUnknown(m)
}

var xxx_messageInfo_AdSlot proto.InternalMessageInfo

func (m *AdSlot) GetAdslotId() string {
	if m != nil && m.AdslotId != nil {
		return *m.AdslotId
	}
	return ""
}

func (m *AdSlot) GetAdslotSize() *Size {
	if m != nil {
		return m.AdslotSize
	}
	return nil
}

func (m *AdSlot) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *AdSlot) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *AdSlot) GetCtkey() string {
	if m != nil && m.Ctkey != nil {
		return *m.Ctkey
	}
	return ""
}

type MobadsRequest struct {
	RequestId            *string                            `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	ApiVersion           *Version                           `protobuf:"bytes,2,opt,name=api_version,json=apiVersion" json:"api_version,omitempty"`
	App                  *App                               `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
	Device               *Device                            `protobuf:"bytes,4,opt,name=device" json:"device,omitempty"`
	Network              *Network                           `protobuf:"bytes,5,opt,name=network" json:"network,omitempty"`
	Gps                  *Gps                               `protobuf:"bytes,6,opt,name=gps" json:"gps,omitempty"`
	Adslot               *AdSlot                            `protobuf:"bytes,7,opt,name=adslot" json:"adslot,omitempty"`
	IsDebug              *bool                              `protobuf:"varint,8,opt,name=is_debug,json=isDebug,def=0" json:"is_debug,omitempty"`
	RequestProtocolType  *MobadsRequest_RequestProtocolType `protobuf:"varint,9,opt,name=request_protocol_type,json=requestProtocolType,enum=baidu.MobadsRequest_RequestProtocolType,def=1" json:"request_protocol_type,omitempty"`
	Page                 *Page                              `protobuf:"bytes,10,opt,name=page" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *MobadsRequest) Reset()         { *m = MobadsRequest{} }
func (m *MobadsRequest) String() string { return proto.CompactTextString(m) }
func (*MobadsRequest) ProtoMessage()    {}
func (*MobadsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{12}
}
func (m *MobadsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobadsRequest.Unmarshal(m, b)
}
func (m *MobadsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobadsRequest.Marshal(b, m, deterministic)
}
func (dst *MobadsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobadsRequest.Merge(dst, src)
}
func (m *MobadsRequest) XXX_Size() int {
	return xxx_messageInfo_MobadsRequest.Size(m)
}
func (m *MobadsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MobadsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MobadsRequest proto.InternalMessageInfo

const Default_MobadsRequest_IsDebug bool = false
const Default_MobadsRequest_RequestProtocolType MobadsRequest_RequestProtocolType = MobadsRequest_HTTP_PROTOCOL_TYPE

func (m *MobadsRequest) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *MobadsRequest) GetApiVersion() *Version {
	if m != nil {
		return m.ApiVersion
	}
	return nil
}

func (m *MobadsRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *MobadsRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *MobadsRequest) GetNetwork() *Network {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *MobadsRequest) GetGps() *Gps {
	if m != nil {
		return m.Gps
	}
	return nil
}

func (m *MobadsRequest) GetAdslot() *AdSlot {
	if m != nil {
		return m.Adslot
	}
	return nil
}

func (m *MobadsRequest) GetIsDebug() bool {
	if m != nil && m.IsDebug != nil {
		return *m.IsDebug
	}
	return Default_MobadsRequest_IsDebug
}

func (m *MobadsRequest) GetRequestProtocolType() MobadsRequest_RequestProtocolType {
	if m != nil && m.RequestProtocolType != nil {
		return *m.RequestProtocolType
	}
	return Default_MobadsRequest_RequestProtocolType
}

func (m *MobadsRequest) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type MetaIndex struct {
	TotalNum             *uint32  `protobuf:"varint,1,opt,name=total_num,json=totalNum" json:"total_num,omitempty"`
	CurrentIndex         *uint32  `protobuf:"varint,2,opt,name=current_index,json=currentIndex" json:"current_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaIndex) Reset()         { *m = MetaIndex{} }
func (m *MetaIndex) String() string { return proto.CompactTextString(m) }
func (*MetaIndex) ProtoMessage()    {}
func (*MetaIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{13}
}
func (m *MetaIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaIndex.Unmarshal(m, b)
}
func (m *MetaIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaIndex.Marshal(b, m, deterministic)
}
func (dst *MetaIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaIndex.Merge(dst, src)
}
func (m *MetaIndex) XXX_Size() int {
	return xxx_messageInfo_MetaIndex.Size(m)
}
func (m *MetaIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaIndex.DiscardUnknown(m)
}

var xxx_messageInfo_MetaIndex proto.InternalMessageInfo

func (m *MetaIndex) GetTotalNum() uint32 {
	if m != nil && m.TotalNum != nil {
		return *m.TotalNum
	}
	return 0
}

func (m *MetaIndex) GetCurrentIndex() uint32 {
	if m != nil && m.CurrentIndex != nil {
		return *m.CurrentIndex
	}
	return 0
}

type MaterialMeta struct {
	CreativeType         *MaterialMeta_CreativeType    `protobuf:"varint,1,opt,name=creative_type,json=creativeType,enum=baidu.MaterialMeta_CreativeType" json:"creative_type,omitempty"`
	InteractionType      *MaterialMeta_InteractionType `protobuf:"varint,2,opt,name=interaction_type,json=interactionType,enum=baidu.MaterialMeta_InteractionType" json:"interaction_type,omitempty"`
	WinNoticeUrl         []string                      `protobuf:"bytes,3,rep,name=win_notice_url,json=winNoticeUrl" json:"win_notice_url,omitempty"`
	ClickUrl             *string                       `protobuf:"bytes,4,opt,name=click_url,json=clickUrl" json:"click_url,omitempty"`
	Title                []byte                        `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	Description          [][]byte                      `protobuf:"bytes,6,rep,name=description" json:"description,omitempty"`
	IconSrc              []string                      `protobuf:"bytes,7,rep,name=icon_src,json=iconSrc" json:"icon_src,omitempty"`
	ImageSrc             []string                      `protobuf:"bytes,8,rep,name=image_src,json=imageSrc" json:"image_src,omitempty"`
	AppPackage           *string                       `protobuf:"bytes,9,opt,name=app_package,json=appPackage" json:"app_package,omitempty"`
	AppSize              *uint32                       `protobuf:"varint,10,opt,name=app_size,json=appSize" json:"app_size,omitempty"`
	VideoUrl             *string                       `protobuf:"bytes,11,opt,name=video_url,json=videoUrl" json:"video_url,omitempty"`
	VideoDuration        *uint32                       `protobuf:"varint,12,opt,name=video_duration,json=videoDuration" json:"video_duration,omitempty"`
	MetaIndex            *MetaIndex                    `protobuf:"bytes,13,opt,name=meta_index,json=metaIndex" json:"meta_index,omitempty"`
	MaterialWidth        *uint32                       `protobuf:"varint,14,opt,name=material_width,json=materialWidth" json:"material_width,omitempty"`
	MaterialHeight       *uint32                       `protobuf:"varint,15,opt,name=material_height,json=materialHeight" json:"material_height,omitempty"`
	BrandName            *string                       `protobuf:"bytes,16,opt,name=brand_name,json=brandName" json:"brand_name,omitempty"`
	AdTitle              *string                       `protobuf:"bytes,17,opt,name=ad_title,json=adTitle" json:"ad_title,omitempty"`
	MaterialSize         *uint32                       `protobuf:"varint,18,opt,name=material_size,json=materialSize" json:"material_size,omitempty"`
	DeeplinkUrl          []byte                        `protobuf:"bytes,19,opt,name=deeplink_url,json=deeplinkUrl" json:"deeplink_url,omitempty"`
	FallbackType         *uint32                       `protobuf:"varint,20,opt,name=fallback_type,json=fallbackType" json:"fallback_type,omitempty"`
	FallbackUrl          []byte                        `protobuf:"bytes,21,opt,name=fallback_url,json=fallbackUrl" json:"fallback_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *MaterialMeta) Reset()         { *m = MaterialMeta{} }
func (m *MaterialMeta) String() string { return proto.CompactTextString(m) }
func (*MaterialMeta) ProtoMessage()    {}
func (*MaterialMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{14}
}
func (m *MaterialMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaterialMeta.Unmarshal(m, b)
}
func (m *MaterialMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaterialMeta.Marshal(b, m, deterministic)
}
func (dst *MaterialMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaterialMeta.Merge(dst, src)
}
func (m *MaterialMeta) XXX_Size() int {
	return xxx_messageInfo_MaterialMeta.Size(m)
}
func (m *MaterialMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_MaterialMeta.DiscardUnknown(m)
}

var xxx_messageInfo_MaterialMeta proto.InternalMessageInfo

func (m *MaterialMeta) GetCreativeType() MaterialMeta_CreativeType {
	if m != nil && m.CreativeType != nil {
		return *m.CreativeType
	}
	return MaterialMeta_NO_TYPE
}

func (m *MaterialMeta) GetInteractionType() MaterialMeta_InteractionType {
	if m != nil && m.InteractionType != nil {
		return *m.InteractionType
	}
	return MaterialMeta_NO_INTERACTION
}

func (m *MaterialMeta) GetWinNoticeUrl() []string {
	if m != nil {
		return m.WinNoticeUrl
	}
	return nil
}

func (m *MaterialMeta) GetClickUrl() string {
	if m != nil && m.ClickUrl != nil {
		return *m.ClickUrl
	}
	return ""
}

func (m *MaterialMeta) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *MaterialMeta) GetDescription() [][]byte {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *MaterialMeta) GetIconSrc() []string {
	if m != nil {
		return m.IconSrc
	}
	return nil
}

func (m *MaterialMeta) GetImageSrc() []string {
	if m != nil {
		return m.ImageSrc
	}
	return nil
}

func (m *MaterialMeta) GetAppPackage() string {
	if m != nil && m.AppPackage != nil {
		return *m.AppPackage
	}
	return ""
}

func (m *MaterialMeta) GetAppSize() uint32 {
	if m != nil && m.AppSize != nil {
		return *m.AppSize
	}
	return 0
}

func (m *MaterialMeta) GetVideoUrl() string {
	if m != nil && m.VideoUrl != nil {
		return *m.VideoUrl
	}
	return ""
}

func (m *MaterialMeta) GetVideoDuration() uint32 {
	if m != nil && m.VideoDuration != nil {
		return *m.VideoDuration
	}
	return 0
}

func (m *MaterialMeta) GetMetaIndex() *MetaIndex {
	if m != nil {
		return m.MetaIndex
	}
	return nil
}

func (m *MaterialMeta) GetMaterialWidth() uint32 {
	if m != nil && m.MaterialWidth != nil {
		return *m.MaterialWidth
	}
	return 0
}

func (m *MaterialMeta) GetMaterialHeight() uint32 {
	if m != nil && m.MaterialHeight != nil {
		return *m.MaterialHeight
	}
	return 0
}

func (m *MaterialMeta) GetBrandName() string {
	if m != nil && m.BrandName != nil {
		return *m.BrandName
	}
	return ""
}

func (m *MaterialMeta) GetAdTitle() string {
	if m != nil && m.AdTitle != nil {
		return *m.AdTitle
	}
	return ""
}

func (m *MaterialMeta) GetMaterialSize() uint32 {
	if m != nil && m.MaterialSize != nil {
		return *m.MaterialSize
	}
	return 0
}

func (m *MaterialMeta) GetDeeplinkUrl() []byte {
	if m != nil {
		return m.DeeplinkUrl
	}
	return nil
}

func (m *MaterialMeta) GetFallbackType() uint32 {
	if m != nil && m.FallbackType != nil {
		return *m.FallbackType
	}
	return 0
}

func (m *MaterialMeta) GetFallbackUrl() []byte {
	if m != nil {
		return m.FallbackUrl
	}
	return nil
}

type Ad struct {
	AdslotId             *string         `protobuf:"bytes,1,opt,name=adslot_id,json=adslotId" json:"adslot_id,omitempty"`
	HtmlSnippet          []byte          `protobuf:"bytes,2,opt,name=html_snippet,json=htmlSnippet" json:"html_snippet,omitempty"`
	MaterialMeta         *MaterialMeta   `protobuf:"bytes,3,opt,name=material_meta,json=materialMeta" json:"material_meta,omitempty"`
	AdKey                *string         `protobuf:"bytes,4,opt,name=ad_key,json=adKey" json:"ad_key,omitempty"`
	AdTracking           []*Tracking     `protobuf:"bytes,5,rep,name=ad_tracking,json=adTracking" json:"ad_tracking,omitempty"`
	MetaGroup            []*MaterialMeta `protobuf:"bytes,6,rep,name=meta_group,json=metaGroup" json:"meta_group,omitempty"`
	MobAdtext            *string         `protobuf:"bytes,7,opt,name=mob_adtext,json=mobAdtext" json:"mob_adtext,omitempty"`
	MobAdlogo            *string         `protobuf:"bytes,8,opt,name=mob_adlogo,json=mobAdlogo" json:"mob_adlogo,omitempty"`
	CpmBid               *uint32         `protobuf:"varint,9,opt,name=cpm_bid,json=cpmBid" json:"cpm_bid,omitempty"`
	Md5                  *string         `protobuf:"bytes,10,opt,name=md5" json:"md5,omitempty"`
	AdslotType           *uint32         `protobuf:"varint,11,opt,name=adslot_type,json=adslotType" json:"adslot_type,omitempty"`
	ChargeType           *uint32         `protobuf:"varint,12,opt,name=charge_type,json=chargeType" json:"charge_type,omitempty"`
	BuyerId              *uint32         `protobuf:"varint,13,opt,name=buyer_id,json=buyerId" json:"buyer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Ad) Reset()         { *m = Ad{} }
func (m *Ad) String() string { return proto.CompactTextString(m) }
func (*Ad) ProtoMessage()    {}
func (*Ad) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{15}
}
func (m *Ad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ad.Unmarshal(m, b)
}
func (m *Ad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ad.Marshal(b, m, deterministic)
}
func (dst *Ad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ad.Merge(dst, src)
}
func (m *Ad) XXX_Size() int {
	return xxx_messageInfo_Ad.Size(m)
}
func (m *Ad) XXX_DiscardUnknown() {
	xxx_messageInfo_Ad.DiscardUnknown(m)
}

var xxx_messageInfo_Ad proto.InternalMessageInfo

func (m *Ad) GetAdslotId() string {
	if m != nil && m.AdslotId != nil {
		return *m.AdslotId
	}
	return ""
}

func (m *Ad) GetHtmlSnippet() []byte {
	if m != nil {
		return m.HtmlSnippet
	}
	return nil
}

func (m *Ad) GetMaterialMeta() *MaterialMeta {
	if m != nil {
		return m.MaterialMeta
	}
	return nil
}

func (m *Ad) GetAdKey() string {
	if m != nil && m.AdKey != nil {
		return *m.AdKey
	}
	return ""
}

func (m *Ad) GetAdTracking() []*Tracking {
	if m != nil {
		return m.AdTracking
	}
	return nil
}

func (m *Ad) GetMetaGroup() []*MaterialMeta {
	if m != nil {
		return m.MetaGroup
	}
	return nil
}

func (m *Ad) GetMobAdtext() string {
	if m != nil && m.MobAdtext != nil {
		return *m.MobAdtext
	}
	return ""
}

func (m *Ad) GetMobAdlogo() string {
	if m != nil && m.MobAdlogo != nil {
		return *m.MobAdlogo
	}
	return ""
}

func (m *Ad) GetCpmBid() uint32 {
	if m != nil && m.CpmBid != nil {
		return *m.CpmBid
	}
	return 0
}

func (m *Ad) GetMd5() string {
	if m != nil && m.Md5 != nil {
		return *m.Md5
	}
	return ""
}

func (m *Ad) GetAdslotType() uint32 {
	if m != nil && m.AdslotType != nil {
		return *m.AdslotType
	}
	return 0
}

func (m *Ad) GetChargeType() uint32 {
	if m != nil && m.ChargeType != nil {
		return *m.ChargeType
	}
	return 0
}

func (m *Ad) GetBuyerId() uint32 {
	if m != nil && m.BuyerId != nil {
		return *m.BuyerId
	}
	return 0
}

type MobadsResponse struct {
	RequestId            *string  `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	ErrorCode            *uint64  `protobuf:"varint,2,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	Ads                  []*Ad    `protobuf:"bytes,3,rep,name=ads" json:"ads,omitempty"`
	ExpirationTime       *uint32  `protobuf:"varint,4,opt,name=expiration_time,json=expirationTime" json:"expiration_time,omitempty"`
	SearchKey            *string  `protobuf:"bytes,5,opt,name=search_key,json=searchKey" json:"search_key,omitempty"`
	ExtStyle             []byte   `protobuf:"bytes,6,opt,name=ext_style,json=extStyle" json:"ext_style,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobadsResponse) Reset()         { *m = MobadsResponse{} }
func (m *MobadsResponse) String() string { return proto.CompactTextString(m) }
func (*MobadsResponse) ProtoMessage()    {}
func (*MobadsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baidu_82fb43fd51839f56, []int{16}
}
func (m *MobadsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobadsResponse.Unmarshal(m, b)
}
func (m *MobadsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobadsResponse.Marshal(b, m, deterministic)
}
func (dst *MobadsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobadsResponse.Merge(dst, src)
}
func (m *MobadsResponse) XXX_Size() int {
	return xxx_messageInfo_MobadsResponse.Size(m)
}
func (m *MobadsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MobadsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MobadsResponse proto.InternalMessageInfo

func (m *MobadsResponse) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *MobadsResponse) GetErrorCode() uint64 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *MobadsResponse) GetAds() []*Ad {
	if m != nil {
		return m.Ads
	}
	return nil
}

func (m *MobadsResponse) GetExpirationTime() uint32 {
	if m != nil && m.ExpirationTime != nil {
		return *m.ExpirationTime
	}
	return 0
}

func (m *MobadsResponse) GetSearchKey() string {
	if m != nil && m.SearchKey != nil {
		return *m.SearchKey
	}
	return ""
}

func (m *MobadsResponse) GetExtStyle() []byte {
	if m != nil {
		return m.ExtStyle
	}
	return nil
}

func init() {
	proto.RegisterType((*Version)(nil), "baidu.Version")
	proto.RegisterType((*App)(nil), "baidu.App")
	proto.RegisterType((*UdId)(nil), "baidu.UdId")
	proto.RegisterType((*Size)(nil), "baidu.Size")
	proto.RegisterType((*Device)(nil), "baidu.Device")
	proto.RegisterType((*WiFiAp)(nil), "baidu.WiFiAp")
	proto.RegisterType((*Network)(nil), "baidu.Network")
	proto.RegisterType((*Gps)(nil), "baidu.Gps")
	proto.RegisterType((*Tracking)(nil), "baidu.Tracking")
	proto.RegisterType((*Video)(nil), "baidu.Video")
	proto.RegisterType((*Page)(nil), "baidu.Page")
	proto.RegisterType((*AdSlot)(nil), "baidu.AdSlot")
	proto.RegisterType((*MobadsRequest)(nil), "baidu.MobadsRequest")
	proto.RegisterType((*MetaIndex)(nil), "baidu.MetaIndex")
	proto.RegisterType((*MaterialMeta)(nil), "baidu.MaterialMeta")
	proto.RegisterType((*Ad)(nil), "baidu.Ad")
	proto.RegisterType((*MobadsResponse)(nil), "baidu.MobadsResponse")
	proto.RegisterEnum("baidu.Device_DeviceType", Device_DeviceType_name, Device_DeviceType_value)
	proto.RegisterEnum("baidu.Device_OsType", Device_OsType_name, Device_OsType_value)
	proto.RegisterEnum("baidu.Network_ConnectionType", Network_ConnectionType_name, Network_ConnectionType_value)
	proto.RegisterEnum("baidu.Network_OperatorType", Network_OperatorType_name, Network_OperatorType_value)
	proto.RegisterEnum("baidu.Gps_CoordinateType", Gps_CoordinateType_name, Gps_CoordinateType_value)
	proto.RegisterEnum("baidu.Tracking_TrackingEvent", Tracking_TrackingEvent_name, Tracking_TrackingEvent_value)
	proto.RegisterEnum("baidu.Video_CopyRight", Video_CopyRight_name, Video_CopyRight_value)
	proto.RegisterEnum("baidu.Video_MaterialFormat", Video_MaterialFormat_name, Video_MaterialFormat_value)
	proto.RegisterEnum("baidu.MobadsRequest_RequestProtocolType", MobadsRequest_RequestProtocolType_name, MobadsRequest_RequestProtocolType_value)
	proto.RegisterEnum("baidu.MaterialMeta_CreativeType", MaterialMeta_CreativeType_name, MaterialMeta_CreativeType_value)
	proto.RegisterEnum("baidu.MaterialMeta_InteractionType", MaterialMeta_InteractionType_name, MaterialMeta_InteractionType_value)
}

func init() { proto.RegisterFile("baidu.proto", fileDescriptor_baidu_82fb43fd51839f56) }

var fileDescriptor_baidu_82fb43fd51839f56 = []byte{
	// 2501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x58, 0xcd, 0x72, 0xdb, 0xc8,
	0x11, 0x16, 0xff, 0x89, 0xe6, 0x8f, 0xb0, 0x63, 0xd9, 0xa6, 0xd7, 0xeb, 0x58, 0x86, 0xe3, 0x8a,
	0x53, 0x95, 0x68, 0x5d, 0x8a, 0x5d, 0xb5, 0xab, 0xd3, 0xd2, 0x24, 0x2c, 0x63, 0x4d, 0x81, 0xaa,
	0x21, 0x64, 0x6d, 0x4e, 0xa8, 0x11, 0x30, 0xa2, 0x10, 0x83, 0x00, 0x02, 0x80, 0xb2, 0xb5, 0x4f,
	0x90, 0x4d, 0x0e, 0x39, 0xb9, 0x2a, 0x87, 0xbd, 0xe6, 0x94, 0x87, 0x48, 0xe5, 0x94, 0x6b, 0xaa,
	0x72, 0x4a, 0xe5, 0x9c, 0xca, 0x35, 0xc9, 0x35, 0x97, 0x54, 0xcf, 0x0c, 0x40, 0xd2, 0xf6, 0x66,
	0x4f, 0x9c, 0xfe, 0xba, 0xa7, 0x7b, 0xd0, 0xdd, 0xd3, 0xdd, 0x43, 0xe8, 0x9c, 0xb1, 0xc0, 0x5f,
	0xee, 0x25, 0x69, 0x9c, 0xc7, 0xa4, 0x21, 0x08, 0xc3, 0x81, 0xd6, 0x4b, 0x9e, 0x66, 0x41, 0x1c,
	0x91, 0x9b, 0xd0, 0x58, 0xb0, 0x5f, 0xc4, 0xe9, 0xa0, 0xb2, 0x5b, 0x79, 0xd8, 0x3b, 0xa8, 0x3c,
	0xa2, 0x92, 0x16, 0x8c, 0x20, 0x8a, 0xd3, 0x41, 0x75, 0xc5, 0x40, 0x5a, 0x32, 0xbc, 0x34, 0x1e,
	0xd4, 0xd6, 0x18, 0x5e, 0x1a, 0x1b, 0xbf, 0xad, 0x40, 0x6d, 0x98, 0x24, 0xe4, 0x26, 0x34, 0x59,
	0x92, 0xb8, 0x81, 0x2f, 0x74, 0x6a, 0x07, 0x5b, 0xb4, 0xc1, 0x92, 0xc4, 0xf2, 0xc9, 0x1d, 0x00,
	0xef, 0x82, 0x45, 0x11, 0x0f, 0x91, 0x89, 0x7a, 0x35, 0xaa, 0x29, 0xc4, 0xf2, 0xc9, 0xa7, 0xd0,
	0xc1, 0x7d, 0x97, 0xf2, 0x64, 0x42, 0x7d, 0x67, 0xbf, 0xbf, 0x27, 0xcf, 0xaf, 0xce, 0x4b, 0x81,
	0x25, 0x49, 0x71, 0xf6, 0xbb, 0x72, 0x43, 0xc2, 0xbc, 0x57, 0x6c, 0xce, 0x07, 0x75, 0xa1, 0x10,
	0x05, 0x8e, 0x25, 0x62, 0xfc, 0xae, 0x0a, 0xf5, 0x13, 0xdf, 0xf2, 0xc9, 0x0e, 0xd4, 0x03, 0xff,
	0x9c, 0x95, 0x07, 0x12, 0x94, 0x40, 0x17, 0x3c, 0x90, 0x27, 0x11, 0xe8, 0x82, 0x07, 0x84, 0x40,
	0x6d, 0xc1, 0x3c, 0x61, 0x1e, 0x41, 0x24, 0xc8, 0x6d, 0x68, 0x23, 0xcf, 0x5d, 0xf8, 0x4f, 0xa4,
	0x99, 0x83, 0x2d, 0xda, 0x42, 0xe4, 0xc8, 0x7f, 0x42, 0xee, 0x02, 0xb0, 0xc8, 0x4f, 0xe3, 0xc0,
	0xc7, 0xcf, 0x6a, 0x28, 0xb6, 0xa6, 0x30, 0xcb, 0x27, 0x1f, 0x43, 0x4b, 0x7c, 0x44, 0xe0, 0x0f,
	0x9a, 0xc5, 0x66, 0x05, 0xe0, 0x19, 0x3c, 0x64, 0xb4, 0x8a, 0x33, 0x20, 0x25, 0xec, 0xf9, 0xe7,
	0x4c, 0xd8, 0x6b, 0x97, 0xf6, 0xfc, 0x73, 0x86, 0xf6, 0x1e, 0x40, 0x4f, 0xe9, 0x0e, 0x7c, 0x21,
	0xa1, 0x29, 0x89, 0x6e, 0x09, 0xa3, 0xd8, 0x27, 0xd0, 0x4e, 0x58, 0x96, 0x25, 0x71, 0x9a, 0x0f,
	0x40, 0x49, 0x94, 0x88, 0x71, 0x00, 0xf5, 0x59, 0xf0, 0x35, 0xc7, 0x68, 0xbe, 0x0e, 0xfc, 0xfc,
	0x62, 0x2d, 0xfe, 0x82, 0x26, 0xb7, 0xa0, 0x79, 0xc1, 0x83, 0xf9, 0x45, 0xbe, 0x4a, 0x00, 0x05,
	0x18, 0xdf, 0xd4, 0xa0, 0x39, 0xe6, 0x97, 0x81, 0xc7, 0xc9, 0xe7, 0xd0, 0xf1, 0xc5, 0xca, 0xcd,
	0xaf, 0x12, 0x2e, 0x94, 0xf4, 0xf7, 0x07, 0x2a, 0x66, 0x52, 0x46, 0xfd, 0x38, 0x57, 0x09, 0xa7,
	0xe0, 0x97, 0x6b, 0xf2, 0x53, 0x68, 0xc5, 0x99, 0xdc, 0x56, 0x15, 0xdb, 0x76, 0x36, 0xb7, 0x4d,
	0x33, 0xb1, 0xa5, 0x19, 0x67, 0x4a, 0x1c, 0xe2, 0xec, 0x7b, 0x92, 0x43, 0x8b, 0xb3, 0x22, 0x37,
	0x06, 0xd0, 0xbc, 0xe4, 0x91, 0x1f, 0xa7, 0x22, 0x5e, 0xdd, 0x83, 0x2d, 0xaa, 0x68, 0x72, 0x03,
	0x1a, 0x8b, 0xd8, 0xe7, 0xa1, 0x88, 0x14, 0x32, 0x24, 0x49, 0xee, 0x42, 0x7d, 0xe9, 0xab, 0x10,
	0x75, 0xf6, 0x3b, 0x4a, 0x35, 0xa6, 0x0f, 0x15, 0x0c, 0xf2, 0x13, 0xe8, 0x64, 0x5e, 0xca, 0x79,
	0xe4, 0x66, 0xc1, 0xd7, 0x5c, 0x44, 0x6c, 0x25, 0x87, 0xce, 0xa4, 0x20, 0xf9, 0xb8, 0x36, 0x4c,
	0x80, 0xd5, 0x87, 0x13, 0x0d, 0x1a, 0xc7, 0xcf, 0xa7, 0xb6, 0xa9, 0x57, 0x08, 0x40, 0xd3, 0x19,
	0x3e, 0x9d, 0x98, 0x8e, 0x5e, 0x25, 0x5d, 0x68, 0xcf, 0x8e, 0x86, 0xd4, 0x71, 0x9d, 0x97, 0x7a,
	0x8d, 0x10, 0xe8, 0x4f, 0x4f, 0x9c, 0xf1, 0x74, 0x4a, 0xdd, 0xd9, 0x88, 0x9a, 0xa6, 0xad, 0xd7,
	0x8d, 0x1f, 0x40, 0x53, 0x3a, 0x82, 0x74, 0xa0, 0x35, 0xb4, 0xc7, 0x74, 0x6a, 0x8d, 0xf5, 0x0a,
	0x69, 0x41, 0xcd, 0x9a, 0xce, 0xf4, 0xaa, 0x11, 0x43, 0xf3, 0x34, 0x78, 0x16, 0x0c, 0x13, 0x72,
	0x1d, 0xaf, 0x9d, 0x8b, 0xa9, 0x2b, 0xb2, 0x1c, 0x2f, 0xdd, 0x11, 0xf3, 0x08, 0x81, 0x7a, 0x9a,
	0x65, 0x32, 0xc9, 0x1b, 0x54, 0xac, 0xc9, 0x4d, 0x68, 0xb1, 0xc4, 0x8d, 0xd8, 0x82, 0x0b, 0x47,
	0x76, 0x69, 0x93, 0x25, 0x36, 0x5b, 0x70, 0x72, 0x0f, 0xba, 0x41, 0xe6, 0x7a, 0x71, 0x14, 0x71,
	0x2f, 0xe7, 0xbe, 0xf0, 0x5d, 0x9b, 0x76, 0x82, 0x6c, 0x54, 0x40, 0xc6, 0x7f, 0x6b, 0xd0, 0xb2,
	0x79, 0xfe, 0x3a, 0x4e, 0x5f, 0xa1, 0xee, 0x20, 0xb9, 0x7c, 0xac, 0x0c, 0x8a, 0x35, 0x79, 0x06,
	0xdb, 0x6a, 0x7f, 0x10, 0x47, 0xeb, 0xe1, 0xbd, 0xa3, 0x3c, 0xa5, 0x36, 0xef, 0x8d, 0x4a, 0x29,
	0x11, 0xe7, 0xbe, 0xb7, 0x41, 0x93, 0x2f, 0xa0, 0x17, 0x27, 0x3c, 0x65, 0x79, 0x9c, 0x4a, 0x2d,
	0x35, 0xa1, 0xe5, 0xf6, 0x3b, 0x5a, 0xa6, 0x4a, 0x46, 0xe8, 0xe8, 0xc6, 0x6b, 0x14, 0x96, 0x07,
	0x8f, 0x87, 0xe1, 0x32, 0x64, 0x29, 0x5e, 0x4c, 0x55, 0x1e, 0x0a, 0xc8, 0xf2, 0xc9, 0x43, 0x68,
	0xbf, 0x0e, 0xce, 0x03, 0x97, 0x25, 0xd9, 0xa0, 0xb1, 0x5b, 0x7b, 0xd8, 0xd9, 0xef, 0x29, 0xed,
	0xd2, 0xa5, 0xb4, 0x85, 0xec, 0x61, 0x92, 0x19, 0x6f, 0x2b, 0xd0, 0xdf, 0x3c, 0x2f, 0xb9, 0x01,
	0x64, 0x34, 0xb5, 0x6d, 0x73, 0xe4, 0x58, 0x53, 0xdb, 0x3d, 0xb1, 0x5f, 0xd8, 0xd3, 0x53, 0x5b,
	0xdf, 0x22, 0x3a, 0x74, 0x47, 0xe6, 0x64, 0x52, 0x22, 0x15, 0x0c, 0x9c, 0x40, 0xf6, 0x0f, 0xf5,
	0x6a, 0x49, 0xfc, 0xec, 0x50, 0xaf, 0x95, 0xc4, 0xe3, 0x43, 0xbd, 0x5e, 0x12, 0x4f, 0x0e, 0xf5,
	0x06, 0x69, 0x43, 0xfd, 0xd4, 0x7a, 0x66, 0xe9, 0x3e, 0xa6, 0x88, 0xe9, 0x3c, 0x37, 0xa9, 0x6d,
	0x3a, 0x3a, 0x27, 0x3d, 0x68, 0xdb, 0xe6, 0xa9, 0xeb, 0xfc, 0xfc, 0xd8, 0xd4, 0xff, 0xd9, 0x32,
	0x62, 0xe8, 0xae, 0x3b, 0x80, 0xec, 0x80, 0xae, 0xec, 0xba, 0xd3, 0x63, 0x93, 0x0e, 0x9d, 0x29,
	0x55, 0x47, 0x7a, 0x6e, 0xd9, 0x43, 0xf7, 0x68, 0xfa, 0xd4, 0x9a, 0x60, 0x0e, 0x7e, 0x04, 0x3d,
	0x89, 0x38, 0xe6, 0xc4, 0x1c, 0x4d, 0x8f, 0xf4, 0xea, 0x4a, 0xe8, 0xc4, 0xb6, 0x10, 0x91, 0xe9,
	0x88, 0x96, 0x57, 0xaa, 0x3c, 0xe3, 0xaf, 0x15, 0xa8, 0x1d, 0x26, 0x19, 0x79, 0x8a, 0x51, 0x8e,
	0x53, 0x3f, 0x88, 0x58, 0xbe, 0x71, 0xf7, 0x6f, 0x29, 0x0f, 0x1e, 0x26, 0xd9, 0xde, 0xa8, 0x94,
	0x28, 0x22, 0xbc, 0x4e, 0x93, 0x4f, 0x40, 0x0b, 0xe3, 0x68, 0x1e, 0xe4, 0x4b, 0x5f, 0xe6, 0x48,
	0x85, 0xae, 0x00, 0xf2, 0x31, 0xb4, 0x43, 0x96, 0x4b, 0x66, 0x4d, 0x30, 0x4b, 0x1a, 0x77, 0xe6,
	0xc1, 0x82, 0x67, 0x39, 0x5b, 0x24, 0x22, 0xae, 0x3d, 0xba, 0x02, 0x8c, 0x47, 0x18, 0xab, 0x0d,
	0x4b, 0x1a, 0x34, 0x4e, 0x0f, 0x67, 0x9f, 0x3d, 0xd6, 0x2b, 0xb8, 0x3c, 0x1c, 0x7d, 0xf9, 0x68,
	0x5f, 0xaf, 0xa2, 0x8f, 0x9f, 0x8e, 0x1f, 0x7d, 0xae, 0xd7, 0x8c, 0xbf, 0x57, 0xa1, 0xed, 0xa4,
	0xcc, 0x7b, 0x15, 0x44, 0x73, 0x32, 0x86, 0x7e, 0xae, 0xd6, 0x2e, 0xbf, 0xe4, 0x51, 0xae, 0xbe,
	0xac, 0xc8, 0xdf, 0x42, 0xb0, 0x5c, 0x98, 0x28, 0x44, 0x7b, 0xf9, 0x3a, 0x89, 0x37, 0xa9, 0xd4,
	0xb2, 0x4c, 0xc3, 0x41, 0x75, 0xb7, 0xf6, 0x50, 0xa3, 0x9d, 0x02, 0x3b, 0x49, 0x43, 0xe3, 0x1f,
	0x15, 0xe8, 0x6d, 0xe8, 0xc0, 0x58, 0x0f, 0xc7, 0xee, 0x68, 0x62, 0x8d, 0x5e, 0xe8, 0x5b, 0x64,
	0x1b, 0x3a, 0xc3, 0xb1, 0x6b, 0x7e, 0x75, 0x3c, 0x9d, 0x9d, 0x50, 0x8c, 0x5a, 0xc1, 0x9e, 0xce,
	0x4c, 0xbd, 0x4a, 0x76, 0xa0, 0xff, 0xd2, 0x1a, 0x9b, 0x53, 0x77, 0x38, 0x76, 0x67, 0xce, 0x90,
	0x3a, 0xfa, 0xaf, 0xde, 0x36, 0xc9, 0xc7, 0xb0, 0x53, 0xa2, 0xcf, 0x4e, 0x26, 0x93, 0xa2, 0x92,
	0x7c, 0xf3, 0xb6, 0x49, 0x08, 0x74, 0x4b, 0x9e, 0x69, 0x8f, 0xf5, 0x5f, 0xbf, 0x6d, 0x92, 0xbb,
	0x70, 0x6b, 0x53, 0x8b, 0x3b, 0x1a, 0xd2, 0xe2, 0x0c, 0xbf, 0x79, 0xdb, 0x24, 0xd7, 0x61, 0x7b,
	0x78, 0x7c, 0x8c, 0xec, 0xf1, 0xf4, 0xd4, 0x9e, 0x4c, 0x87, 0x63, 0xfd, 0x5f, 0xdf, 0x36, 0xd1,
	0xba, 0x82, 0x2d, 0x7b, 0xe6, 0x0c, 0x27, 0x13, 0xfd, 0xdf, 0xdf, 0x36, 0xc9, 0x35, 0xe8, 0x29,
	0x74, 0x38, 0x72, 0xac, 0x97, 0xa6, 0xfe, 0x9f, 0x6f, 0x9b, 0xc6, 0x9f, 0xab, 0xd0, 0x78, 0x19,
	0xf8, 0x3c, 0x26, 0x3b, 0xd0, 0xc8, 0x83, 0x3c, 0x94, 0xb9, 0xd2, 0xa5, 0x92, 0x20, 0x0f, 0x00,
	0xef, 0x7e, 0xce, 0xa3, 0xdc, 0x0d, 0x79, 0x34, 0xcf, 0x2f, 0x64, 0xc7, 0xa1, 0x3d, 0x85, 0x4e,
	0x04, 0x48, 0x1e, 0x83, 0xe6, 0xc5, 0xc9, 0x55, 0x2a, 0x7a, 0x92, 0x2c, 0x06, 0x37, 0x8a, 0xfa,
	0x8f, 0xda, 0xf7, 0x46, 0x71, 0x72, 0x45, 0x91, 0x4b, 0x57, 0x82, 0x64, 0x0c, 0xdb, 0x0b, 0x96,
	0xf3, 0x34, 0x60, 0xa1, 0x7b, 0x1e, 0xa7, 0x0b, 0x96, 0x0f, 0xea, 0xbb, 0xb5, 0xb5, 0x42, 0x22,
	0xf7, 0x1e, 0x29, 0x99, 0x67, 0x42, 0x84, 0xf6, 0x17, 0x1b, 0xb4, 0xf1, 0x05, 0x68, 0xa5, 0x76,
	0x71, 0x51, 0xa9, 0x6b, 0x63, 0x35, 0xdf, 0xc2, 0x98, 0x8c, 0xa8, 0x6b, 0x7e, 0x65, 0xcd, 0x1c,
	0x59, 0xdb, 0x47, 0xd4, 0x3d, 0x39, 0x1c, 0xc9, 0xda, 0x3e, 0xa2, 0xae, 0xb8, 0x41, 0x7a, 0xcd,
	0x18, 0x41, 0x7f, 0xd3, 0x06, 0xde, 0x41, 0xe9, 0x79, 0x67, 0x34, 0x71, 0x8f, 0x8e, 0x1f, 0xeb,
	0x1d, 0xbc, 0x83, 0x2b, 0xc8, 0x99, 0xe9, 0x5d, 0x54, 0xa2, 0x90, 0x99, 0xde, 0x33, 0xfe, 0x56,
	0x81, 0xfa, 0x31, 0x9b, 0x73, 0xa2, 0x43, 0x0d, 0x93, 0x4a, 0xba, 0x11, 0x97, 0x2b, 0xd7, 0x56,
	0xd7, 0x5d, 0x7b, 0x07, 0x20, 0x8b, 0x97, 0xa9, 0xc7, 0x45, 0x0e, 0xca, 0x5a, 0xaf, 0x49, 0xe4,
	0x24, 0x0d, 0xc5, 0x40, 0xa6, 0x3c, 0x5f, 0x16, 0x48, 0x4d, 0x21, 0x96, 0x4f, 0x7e, 0x0c, 0x7a,
	0xc1, 0xf6, 0x58, 0xce, 0xe7, 0x71, 0x7a, 0x25, 0xea, 0x64, 0x97, 0x6e, 0x2b, 0x7c, 0xa4, 0x60,
	0x72, 0x1f, 0x7a, 0x65, 0x0c, 0xd9, 0x19, 0x0f, 0x07, 0x4d, 0x21, 0xd7, 0x2d, 0x42, 0x88, 0x18,
	0xb9, 0x0d, 0x1a, 0x5b, 0xe6, 0x17, 0xb1, 0x28, 0xc7, 0x62, 0xe0, 0xa1, 0x6d, 0x09, 0x58, 0xbe,
	0xf1, 0xfb, 0x0a, 0x34, 0x87, 0xfe, 0x2c, 0x8c, 0x73, 0x21, 0xe7, 0x67, 0x61, 0x9c, 0x97, 0x33,
	0x24, 0x6d, 0x4b, 0xc0, 0x12, 0x5d, 0x58, 0x31, 0x45, 0x17, 0xae, 0x7e, 0xa0, 0x0b, 0x4b, 0xbe,
	0x18, 0x6f, 0x6e, 0x40, 0x33, 0x8f, 0x93, 0xc0, 0xcb, 0x06, 0x35, 0x71, 0x20, 0x45, 0x11, 0x03,
	0x1a, 0x97, 0x18, 0x78, 0xf1, 0xd1, 0x9d, 0xfd, 0xee, 0x7a, 0x32, 0x50, 0xc9, 0x42, 0x97, 0x7a,
	0xf9, 0x2b, 0x7e, 0x25, 0x47, 0x3a, 0x2a, 0x09, 0xe3, 0x0f, 0x75, 0xe8, 0x1d, 0xc5, 0x67, 0xcc,
	0xcf, 0x28, 0xff, 0xe5, 0x92, 0x67, 0x39, 0x7a, 0x31, 0x95, 0xcb, 0xd5, 0x79, 0x35, 0x85, 0x14,
	0x63, 0x6d, 0x50, 0x4e, 0x2e, 0xd5, 0xef, 0x1a, 0x6b, 0x83, 0x62, 0x74, 0xf9, 0x04, 0x6a, 0x2c,
	0x49, 0xd4, 0x88, 0x03, 0x4a, 0x70, 0x98, 0x24, 0x14, 0x61, 0xf2, 0x00, 0x9a, 0x72, 0x88, 0x52,
	0x47, 0xef, 0x6d, 0x4c, 0x4d, 0x54, 0x31, 0xc9, 0x43, 0x68, 0x45, 0xb2, 0x45, 0x8a, 0xe3, 0xaf,
	0x2c, 0xaa, 0xc6, 0x49, 0x0b, 0x36, 0x9a, 0x9b, 0x27, 0x99, 0x1a, 0x7b, 0x60, 0x55, 0xbe, 0x29,
	0xc2, 0x68, 0x4e, 0xba, 0x53, 0xcd, 0x3b, 0x85, 0x39, 0x19, 0x2a, 0xaa, 0x98, 0x64, 0x17, 0xda,
	0x41, 0xe6, 0xfa, 0xfc, 0x6c, 0x39, 0x17, 0x03, 0x6b, 0xfb, 0xa0, 0x71, 0xce, 0xc2, 0x8c, 0xd3,
	0x56, 0x90, 0x8d, 0x11, 0x25, 0x09, 0x5c, 0x2f, 0xbc, 0x24, 0xde, 0x22, 0x5e, 0x1c, 0xca, 0xbe,
	0xa1, 0x89, 0xab, 0xfc, 0x50, 0xe9, 0xdd, 0x70, 0xed, 0x9e, 0xfa, 0x3d, 0x56, 0x1b, 0xb0, 0x98,
	0x1f, 0x90, 0xe7, 0x8e, 0x73, 0xec, 0x1e, 0xd3, 0xa9, 0x33, 0x1d, 0x4d, 0x27, 0xa2, 0x15, 0xd2,
	0x6b, 0xe9, 0xfb, 0x82, 0x38, 0xd0, 0x25, 0xf8, 0x2e, 0x80, 0x8d, 0x14, 0xc1, 0xfb, 0x43, 0x05,
	0xc3, 0x60, 0x70, 0xed, 0x03, 0x06, 0xc8, 0x2d, 0xb8, 0x5e, 0x34, 0xd1, 0x0d, 0x2b, 0xfa, 0x16,
	0x36, 0xfd, 0xf7, 0xad, 0xeb, 0x15, 0x72, 0x13, 0xae, 0x21, 0x3e, 0x7b, 0x87, 0x51, 0x35, 0x8e,
	0x40, 0x3b, 0xe2, 0x39, 0xb3, 0x22, 0x9f, 0xbf, 0xc1, 0xbc, 0xce, 0xe3, 0x9c, 0x85, 0x6e, 0xb4,
	0x5c, 0xc8, 0x79, 0x9b, 0xb6, 0x05, 0x60, 0x2f, 0x17, 0xe2, 0x06, 0x2d, 0xd3, 0x54, 0xdc, 0x45,
	0x94, 0x56, 0x45, 0xb0, 0xab, 0x40, 0xa1, 0xc1, 0xf8, 0x63, 0x0b, 0xba, 0x45, 0x19, 0x41, 0xbd,
	0xc4, 0x84, 0x9e, 0x97, 0x72, 0x96, 0x07, 0x97, 0x1b, 0x5d, 0x78, 0xb7, 0xf0, 0xe6, 0x9a, 0xec,
	0xde, 0x48, 0x09, 0xca, 0x51, 0xc9, 0x5b, 0xa3, 0x88, 0x0d, 0x7a, 0x10, 0xe5, 0x3c, 0x65, 0xef,
	0x4d, 0x6d, 0xf7, 0x3f, 0xa4, 0xc9, 0x5a, 0xc9, 0x0a, 0x65, 0xdb, 0xc1, 0x26, 0x40, 0x7e, 0x08,
	0xfd, 0xd7, 0x41, 0xe4, 0x46, 0x71, 0x1e, 0x94, 0xb5, 0x07, 0xfb, 0x5f, 0xf7, 0x75, 0x10, 0xd9,
	0x02, 0xc4, 0xf2, 0x73, 0x1b, 0x34, 0x2f, 0x0c, 0xbc, 0x57, 0x42, 0x40, 0x56, 0x9f, 0xb6, 0x00,
	0x4e, 0xd6, 0x0b, 0x5a, 0x63, 0xbd, 0xa0, 0xed, 0xe2, 0x7b, 0x23, 0xf3, 0xd2, 0x20, 0x41, 0x5b,
	0xaa, 0xca, 0xac, 0x43, 0xe4, 0x16, 0xb4, 0x03, 0x2f, 0x8e, 0xdc, 0x2c, 0xf5, 0x06, 0x2d, 0x61,
	0xb4, 0x85, 0xf4, 0x2c, 0xc5, 0x57, 0x9c, 0x16, 0x2c, 0xd8, 0x9c, 0x0b, 0x5e, 0x5b, 0xf0, 0xda,
	0x02, 0x40, 0xe6, 0x3b, 0x8f, 0x49, 0xed, 0xdd, 0xc7, 0x24, 0x2a, 0x46, 0x01, 0x51, 0x75, 0x40,
	0xc4, 0xa6, 0xc5, 0x92, 0x44, 0x54, 0x99, 0xdb, 0xa0, 0x89, 0x92, 0x21, 0x3e, 0xa4, 0x23, 0x3f,
	0x44, 0x00, 0xf8, 0x21, 0x0f, 0xa0, 0x2f, 0x99, 0xfe, 0x32, 0x65, 0xe2, 0xd4, 0x5d, 0xd9, 0xde,
	0x04, 0x3a, 0x56, 0x20, 0xf9, 0x14, 0x60, 0xc1, 0x73, 0xa6, 0x82, 0xdf, 0x13, 0x39, 0xab, 0x17,
	0xce, 0x2f, 0x52, 0x88, 0x6a, 0x8b, 0x32, 0x9b, 0x1e, 0x40, 0xd9, 0xa5, 0x5c, 0xf9, 0x84, 0xeb,
	0x4b, 0xbd, 0x05, 0x7a, 0x2a, 0xde, 0x71, 0x3f, 0x5a, 0x6b, 0x80, 0xea, 0x41, 0xb7, 0x2d, 0xe4,
	0xca, 0xdd, 0xcf, 0x05, 0x8a, 0x65, 0xec, 0x2c, 0x65, 0x91, 0x2f, 0xdf, 0x05, 0xba, 0x2c, 0x63,
	0x02, 0x11, 0x4f, 0x03, 0xfc, 0x7c, 0xdf, 0x95, 0x21, 0xf9, 0x48, 0x30, 0x5b, 0xcc, 0x77, 0x44,
	0x50, 0xee, 0x43, 0x69, 0x53, 0xba, 0x87, 0xc8, 0xd4, 0x2d, 0x40, 0xe1, 0xa3, 0x7b, 0xd0, 0xf5,
	0x39, 0x4f, 0xc2, 0x20, 0x92, 0xf1, 0xbe, 0x26, 0xc2, 0xda, 0x29, 0x30, 0xf4, 0xd4, 0x7d, 0xe8,
	0x9d, 0xb3, 0x30, 0x3c, 0x63, 0xde, 0x2b, 0x99, 0x82, 0x3b, 0x52, 0x4f, 0x01, 0x8a, 0xd4, 0xba,
	0x07, 0x25, 0x2d, 0xf4, 0x5c, 0x97, 0x7a, 0x0a, 0x0c, 0x07, 0xab, 0x2f, 0xa1, 0xbb, 0x9e, 0xeb,
	0xd8, 0xb0, 0xed, 0x69, 0x71, 0x85, 0xdb, 0x50, 0x77, 0xcc, 0xaf, 0x1c, 0x39, 0x0a, 0x5a, 0x47,
	0xc3, 0x43, 0x9c, 0xa5, 0x7a, 0xa0, 0x21, 0xe8, 0x5a, 0xa3, 0xa9, 0xad, 0xd7, 0x90, 0x23, 0xba,
	0xae, 0x5e, 0x37, 0x6c, 0xd8, 0x7e, 0x27, 0xdb, 0x71, 0x2e, 0xb6, 0xa7, 0xae, 0x65, 0x3b, 0x26,
	0x1d, 0x8a, 0xe9, 0x5f, 0xdf, 0x42, 0x13, 0xb3, 0x13, 0xfa, 0xcc, 0xb2, 0x0f, 0xe5, 0x9c, 0x56,
	0xce, 0x4a, 0x62, 0x0e, 0x18, 0x9b, 0xe6, 0xf1, 0xc4, 0xb2, 0x5f, 0xe8, 0x35, 0xe3, 0x4f, 0x35,
	0xa8, 0x0e, 0xfd, 0xff, 0xdf, 0xe2, 0xee, 0x41, 0xf7, 0x22, 0x5f, 0x84, 0x6e, 0x16, 0x05, 0x49,
	0xc2, 0x73, 0xd5, 0xd2, 0x3b, 0x88, 0xcd, 0x24, 0x44, 0x3e, 0x5b, 0x73, 0x39, 0xa6, 0x84, 0xea,
	0x16, 0xd7, 0x3e, 0x70, 0x5b, 0x57, 0x71, 0x10, 0x15, 0x03, 0x9f, 0x89, 0xbe, 0x8b, 0x6d, 0xad,
	0xae, 0x9e, 0x89, 0xfe, 0x0b, 0x7e, 0x45, 0x1e, 0x61, 0x5b, 0x75, 0x8b, 0xf1, 0x54, 0x3d, 0x87,
	0xb6, 0xdf, 0x19, 0x79, 0xb1, 0xb5, 0x96, 0x73, 0xf2, 0xbe, 0x4a, 0xd8, 0x79, 0x1a, 0x2f, 0x13,
	0x71, 0x13, 0xbf, 0xc3, 0xbe, 0xc8, 0xd9, 0x43, 0x94, 0xc2, 0x1c, 0x5b, 0xc4, 0x67, 0x2e, 0xf3,
	0x73, 0xfe, 0x26, 0x57, 0x23, 0x80, 0xb6, 0x88, 0xcf, 0x86, 0x02, 0x58, 0xb1, 0xc3, 0x78, 0x1e,
	0xcb, 0x3f, 0x3e, 0x14, 0x1b, 0x01, 0x7c, 0xb6, 0x7a, 0xc9, 0xc2, 0x3d, 0x0b, 0x7c, 0x71, 0x3d,
	0x7b, 0xb4, 0xe9, 0x25, 0x8b, 0xa7, 0x81, 0x8f, 0xe3, 0xd0, 0xc2, 0x7f, 0x22, 0xff, 0xe5, 0xa0,
	0xb8, 0x14, 0xb7, 0x59, 0xfa, 0x57, 0x24, 0x52, 0x47, 0x88, 0xab, 0xc1, 0xa0, 0x7c, 0x1c, 0x5e,
	0xb0, 0x74, 0xae, 0xca, 0xa6, 0xbc, 0x92, 0x20, 0x21, 0xd5, 0x05, 0xda, 0x67, 0xcb, 0x2b, 0x2e,
	0x66, 0x95, 0x9e, 0xbc, 0xee, 0x82, 0xb6, 0x7c, 0xe3, 0x2f, 0x15, 0xe8, 0x17, 0x7d, 0x2a, 0x4b,
	0xe2, 0x28, 0xe3, 0xdf, 0x37, 0x03, 0xdc, 0x01, 0xe0, 0x69, 0x1a, 0xa7, 0xae, 0x17, 0xab, 0xb7,
	0x4e, 0x9d, 0x6a, 0x02, 0x19, 0xc5, 0x3e, 0xd6, 0x8f, 0x1a, 0xf3, 0xe5, 0x88, 0xd2, 0xd9, 0xd7,
	0xca, 0x0e, 0x4b, 0x11, 0xc5, 0x0b, 0xcc, 0xdf, 0x24, 0x81, 0x2c, 0x13, 0x2e, 0x3e, 0x73, 0xd4,
	0x93, 0xa7, 0xbf, 0x82, 0x9d, 0x60, 0x21, 0x87, 0x3d, 0xce, 0x52, 0xef, 0xc2, 0x5d, 0x0d, 0x2d,
	0x9a, 0x44, 0x30, 0xc2, 0xb7, 0x41, 0xe3, 0x6f, 0x72, 0x37, 0xcb, 0xaf, 0x42, 0x2e, 0xba, 0x7d,
	0x97, 0xb6, 0xf9, 0x9b, 0x7c, 0x86, 0xf4, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xc5, 0x47,
	0x7f, 0x26, 0x14, 0x00, 0x00,
}
